# Background
background_opacity 	0.90
background          #1E1E2E
foreground          #D9E0EE

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Tabs
tab_bar_style                 powerline
tab_powerline_style           slanted
tab_title_template            "{sup.index} {title}"
active_tab_foreground         #161320
active_tab_background         #F5C2E7
inactive_tab_foreground       #D9E0EE
inactive_tab_background       #161320
tab_bar_background            #1E1E2E

# Fonts
font_size		15
# font_family FiraCode Nerd Font
font_family DaddyTimeMono Nerd Font
# font_family		DejaVu Sans Mono for Powerline

# высота строки
modify_font cell_height 135%
# modify_font cell_height 100%

# этот шрифт отвечает за иконку в строке приглашения starship
# при условии, что используется шрифт FiraCode Nerd Font
# symbol_map U+279c DejaVu Sans Mono for Powerline Bold 
# symbol_map U+279c Symbols Nerd Font 

# BEGIN_KITTY_THEME
# Solarized Dark

# narrow_symbols U+E0A0-U+E0A3,U+E0C0-U+E0C7 1
disabled_ligatures never
open_url_with chromium
