# Background
background_opacity 	0.95

# Fonts
font_size		14
font_family FiraCode Nerd Font
# высота строки
modify_font cell_height 135%

# font_family		DejaVu Sans Mono for Powerline

symbol_map U+279c DejaVu Sans Mono for Powerline 

# BEGIN_KITTY_THEME
# Solarized Dark

include current-theme.conf
# END_KITTY_THEME

# narrow_symbols U+E0A0-U+E0A3,U+E0C0-U+E0C7 1

disabled_ligatures never

open_url_with chromium

