# Don't print a new line at the start of the prompt
# add_newline = true
add_newline = false

format = "$username$os$directory$all"
# format = "$username$os$directory$git_branch$git_status$git_commit$git_metrics$docker_context"

# [line_break]
# disabled = true

# Replaces the default "❯" symbol in the prompt with "➜"
[character]                             # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"      # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
#SPACESHIP_NODE_SHOW= true

[username]
style_user = "bold green"
show_always = true

[os]
disabled = false
# symbol = " "
# format = "on [ ]($style)"
# style = "bold blue"

[os.symbols]
# Arch = "🐧 "
Arch = "  "
# Windows = " "

[hostname]
ssh_only = false
disabled = true 
format =  "[$hostname](bold red) "

[nodejs]
symbol = "⛏️ "
# symbol = "🧩 "
# symbol = "🍕 "

[solidity]
symbol = "💎 "
