-- Base
require("core.mappings")
require("core.plugins")
require("core.config")

-- Plugins
require("plugins.treesitter")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.telescope")
require("plugins.formatter")
require("plugins.colorizer")
require("plugins.nvimtree")
require("plugins.gitsigns")
require("plugins.comment")
require("plugins.conform")
require("plugins.lualine")
require("plugins.autotag")
require("plugins.mason")
require("plugins.theme")
require("plugins.lsp")
require("plugins.cmp")
